name:                sccHaskell
version:             1.0.0.0
github:              "randrade23/sccHaskell"
license:             BSD3
author:              "Rui Andrade & Mário Florido"
maintainer:          "rui.andrade@fc.up.pt"
copyright:           "2018 Rui Andrade & Mário Florido"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/randrade23/sccHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- ghc
- ghc-paths
- array
- parsec
- haskell-src-meta
- process
- template-haskell

library:
  source-dirs: src

executables:
  sccHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sccHaskell
